name: PR Labeler
on:
    - pull_request_target
jobs:
    triage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/labeler@v4
              with:
                  repo-token: ${{ secrets.IQ_GITHUB_TOKEN }}
                  configuration-path: .github/labeler.yml
                  sync-labels: true
